iop4.py: allow select by astrosource
juanep97/iop4 pull request #105
Opened 2024-05-06 12:22 UTC by juanep97

2024-05-06 14:45 UTC, morcuended requested changes

2024-05-06 14:45 UTC, morcuended commented on iop4lib/iop4.py
> +    parser.add_argument('--astrosource', dest='astrosource', type=str, default=None, help='<Optional> Select files only of this source')
No need to specify the dest if it is the same as the command line argument

2024-05-06 14:45 UTC, morcuended commented on iop4lib/iop4.py
> +    parser.add_argument('--astrosource', dest='astrosource', type=str, default=None, help='<Optional> Select files only of this source')
```suggestion
    parser.add_argument('--astrosource', type=str, default=None, help='<Optional> Select files only of this source')
```

2024-05-06 14:45 UTC, morcuended commented on iop4lib/iop4.py
> +def process_astrosource(args):
Even if the function name is quite descriptive, I would add a docstring describing it, maybe with some more detailed Notes as well with the different things it can do and args combinations (retry, recompute, etc).

2024-05-06 14:45 UTC, morcuended commented on iop4lib/iop4.py
> +    # filter files who have identified this source (in sources_in_field) or have this source as header_hintobject
```suggestion
    # filter files that have identified this source (in sources_in_field) or have this source as header_hintobject
```

2024-05-06 14:45 UTC, morcuended commented on iop4lib/iop4.py
> +        process_astrosource(args)
Is the astrosource option supposed to be checked before running an entire epoch?

2024-05-06 14:45 UTC, morcuended commented on iop4lib/iop4.py
> +    logger.info(f"Found {len(redfL)} reduced fits for astrosource {args.astrosource}")
For logging, it is recommended to use lazy formatting instead of f-strings, which is more costly, but the formatting supported by the logging messages itself, since these are "lazy" (if the message is not printed, the potentially expensive formatting is not done). However f-strings are more readable.

```
logger.info(f"Found %d reduced fits for astrosource %s", len(redfL), args.astrosource)
```

2024-05-07 21:51 UTC, juanep97 commented on iop4lib/iop4.py
> +        process_astrosource(args)
What do you mean? Why do we check it here?

2024-05-08 09:17 UTC, morcuended commented on iop4lib/iop4.py
> +    logger.info(f"Found {len(redfL)} reduced fits for astrosource {args.astrosource}")
just to bear this in mind, it can be decided/done somewhere else

2024-05-08 09:19 UTC, morcuended commented on iop4lib/iop4.py
> +        process_astrosource(args)
I meant if the selection of the source files was being done before running the entire epoch, which is what you are saying.

2024-05-09 14:57 UTC, juanep97 commented
```
        for redf in redfL:
            redf.compute_photometry()
            redf.compute_polarimetry()
```
(Re)computing polarimetry results can not be done only from a single reduced file. Polarimetry groups need to be re-computed possibly, and then the polarimetric results need to be computed for the whole group.

2024-11-13 04:22 UTC, merged