Action to add calibrators from PANSTARRS
juanep97/iop4 pull request #142
Opened 2024-10-07 02:37 UTC by juanep97

This PR adds an action to the AstroSource admin for automatically adding calibrators from PANSTARRS.

<img width="497" alt="imagen" src="https://github.com/user-attachments/assets/cdffa7ca-e99c-4417-b2e1-47a56fcab386">

2024-10-07 06:43 UTC, joteros requested changes
Use ApMag instead of PSFMag
Set condition on the number of observations of each star, ApMagNpt>=5
Set condition on the ApMagStd<0.01

If with those conditions, we cannot find stars, then relax in a second step iteration those for ApMagNpt and ApMagStd

2024-10-08 00:15 UTC, juanep97 commented
@joteros what do you think of those constraints? I think they are a reasonable minimum. Then we just take the top 10 results, by number of observations.

2024-10-08 07:11 UTC, joteros commented
Looks good to me. I usually use as minimum magnitude allowed 17 instead of 16, but this is a minor change. 
At some point we should add a second iteration search in case the search does not find any star in the FoV, relaxing a bit the criteria (it happened to me a couple of times), increasing the Std threshold, lowering the minimum magnitude and the number of observations required, but this can be done afterwards.

2024-10-08 07:13 UTC, joteros reviewed
Looks good to me. I usually use as minimum magnitude allowed 17 instead of 16, but this is a minor change.
At some point we should add a second iteration search in case the search does not find any star in the FoV, relaxing a bit the criteria (it happened to me a couple of times), increasing the Std threshold, lowering the minimum magnitude and the number of observations required, but this can be done afterwards.

2024-10-08 08:07 UTC, morcuended commented on iop4admin/modeladmins/astrosource.py
> +        idx = (11.0 <= catalog_data["rMeanApMag"]) & (catalog_data["rMeanApMag"] <= 16.0)
I would define these two magnitude minimum and maximum values at the beginning of the file. Or at least a comment explaining these cuts

2024-10-08 08:07 UTC, morcuended commented on iop4admin/modeladmins/astrosource.py
> +        idx = idx & (catalog_data["rMeanApMagNpt"] > 5)
what is `rMeanApMagNpt`, and why the value 5? (I would define it as well at the top)

2024-10-08 08:07 UTC, morcuended commented on iop4admin/modeladmins/astrosource.py
> +
Maybe add log info ("Filtering stars with magnitude between {MIN_R_MAGNITUDE} and {MAX_R_MAGNITUDE}")

2024-10-08 08:07 UTC, morcuended commented on iop4admin/modeladmins/astrosource.py
> +            try:
To make it clear I would add here a comment say also `# SDSS to Johnson-Cousins transformation by Lupton (2005)`

2024-10-08 12:13 UTC, juanep97 commented on iop4admin/modeladmins/astrosource.py
> +        idx = idx & (catalog_data["rMeanApMagNpt"] > 5)
It is the number of observations for each aperture magnitude. I have defined the constraints at the top of the function and added some comments. The number 5 is arbitrary, but it is just the minimum. We take the top 10 results by this number.

2024-10-08 12:13 UTC, juanep97 commented on iop4admin/modeladmins/astrosource.py
> +        idx = (11.0 <= catalog_data["rMeanApMag"]) & (catalog_data["rMeanApMag"] <= 16.0)
Done.

2024-10-08 12:14 UTC, juanep97 commented on iop4admin/modeladmins/astrosource.py
> +            try:
Done

2024-10-08 12:14 UTC, juanep97 commented on iop4admin/modeladmins/astrosource.py
> +
Done.

2024-10-08 12:16 UTC, joteros approved these changes

2024-10-08 12:18 UTC, juanep97 commented
> Looks good to me. I usually use as minimum magnitude allowed 17 instead of 16, but this is a minor change. At some point we should add a second iteration search in case the search does not find any star in the FoV, relaxing a bit the criteria (it happened to me a couple of times), increasing the Std threshold, lowering the minimum magnitude and the number of observations required, but this can be done afterwards.

I am hesitant to perform this automatic lowering of the quality constraints, since the user would not know about this and have no choice, at least through this GUI (if we added an interactive tab for it, perhaps). Another option would be to add two different actions, with two different set of constraints (e.g. "Automatically add field stars from PanSTARRS" and "Automatically add field stars from PanSTARRS (relaxed)").

2024-10-08 12:22 UTC, joteros commented
> > Looks good to me. I usually use as minimum magnitude allowed 17 instead of 16, but this is a minor change. At some point we should add a second iteration search in case the search does not find any star in the FoV, relaxing a bit the criteria (it happened to me a couple of times), increasing the Std threshold, lowering the minimum magnitude and the number of observations required, but this can be done afterwards.
> 
> I am hesitant to perform this automatic lowering of the quality constraints, since the user would not know about this and would have no choice, at least through this GUI (if we added an interactive tab for it, perhaps). Another option would be to add two different actions, with two different sets of constraints (e.g. "Automatically add field stars from PanSTARRS" and "Automatically add field stars from PanSTARRS (relaxed)").

Sounds like a good solution. In any case, as I said this can be implemented (and even refined) afterwards, and my expectation is that it won't happen too often

2024-10-08 13:24 UTC, merged