Improve docs [WIP]
juanep97/iop4 pull request #70
Opened 2024-01-09 14:34 UTC by juanep97

2024-01-09 14:40 UTC, juanep97 commented
@morcuended what do you recommend between available options (pure .ipynb + nbspinx, .myst + myst_nb, .py + sphinx-gallery)?

2024-02-16 11:25 UTC, morcuended commented
maybe sphinx-gallery?

2024-02-26 15:36 UTC, juanep97 commented
Tests are passing in local. CI tests are failing, not sure why now (I don't see the usual can't load astrometry file). Hopefully it will be solved when we implement the self-hosted runner once and for all.

2024-02-26 15:47 UTC, juanep97 commented
> "TypeError: loading "/home/runner/.astrometry_cache/5200/index-5202-04.fits" failed"

In the last run only, but not in the previous one, no?

2024-02-26 15:50 UTC, morcuended commented
review in progress

2024-02-26 16:20 UTC, rlopezcoto commented
>In the last run only, but not in the previous one, no?

do you mean in other CI runs?

2024-03-19 17:56 UTC, morcuended requested changes
Looks really nice! I just left some typos that can be committed in a single batch

2024-03-19 17:56 UTC, morcuended commented on docs/iop4_concepts.rst
> +After login in with the credentials that you suplied in during the `set up`
```suggestion
After login in with the credentials that you supplied during the `set up` 
```

2024-03-19 17:56 UTC, morcuended commented on docs/iop4_concepts.rst
>  The procedure to analyze and reduce photometric and polarimetric images is similar from one
```suggestion
The procedure to analyze and reduce photometric and polarimetric images is similar to one 
```

2024-03-19 17:56 UTC, morcuended commented on docs/iop4_concepts.rst
> +details from the main code. Telescope-specific code to is relegated to the :code:`iop4lib.telescopes` submodule, while
```suggestion
details from the main code. Telescope-specific code is relegated to the :code:`iop4lib.telescopes` submodule, while 
```

2024-03-19 17:56 UTC, morcuended commented on docs/serving_iop4_in_production.rst
> +a real server is a complex task and depends on how do you want to integrate
```suggestion
a real server is a complex task and depends on how you want to integrate
```

2024-03-19 17:56 UTC, morcuended commented on docs/serving_iop4_in_production.rst
> +will be using, and ``/path/to/static/`` should be accesible by the user
```suggestion
will be using, and ``/path/to/static/`` should be accessible by the user 
```

2024-03-19 17:56 UTC, morcuended commented on docs/sphinxext/thumbnail_gallery.py
> +    nb_paths = glob(f"recipes/*.py")
`f` not needed?

2024-03-19 17:56 UTC, morcuended commented on docs/sphinxext/thumbnail_gallery.py
> +Sphinx plugin to run generate a gallery for notebooks
This was needed because sphinxext was not completely working for this use case, right?

2024-03-19 17:56 UTC, morcuended commented on docs/recipes/02_database_queries.py
> +# - AperPhotResult: result of performing aperture photometry on a image. It is
```suggestion
# - AperPhotResult: result of performing aperture photometry on an image. It is 
```

2024-03-19 17:56 UTC, morcuended commented on docs/recipes/02_database_queries.py
> +# Each of the models are linked through attributes to the rest of models.
```suggestion
# Each of the models is linked through attributes to the rest of models.
```

2024-03-19 17:56 UTC, morcuended commented on docs/recipes/02_database_queries.py
> +# In addition, we have inadvertely used the `field__query` syntax to access
```suggestion
# In addition, we have inadvertently used the `field__query` syntax to access 
```

2024-03-19 17:56 UTC, morcuended commented on docs/recipes/02_database_queries.py
> +# methods or related fields. At the begining we used `filename__icontains`
```suggestion
# methods or related fields. At the beginning we used `filename__icontains`
```

2024-03-19 17:56 UTC, morcuended commented on docs/recipes/03_manual_reduction.py
> +# The most common way to use IOP4 should by launching the `iop4` command to
```suggestion
# The most common way to use IOP4 is by launching the `iop4` command to 
```

2024-03-19 17:56 UTC, morcuended commented on docs/recipes/03_manual_reduction.py
> +# We might be interested to download all files from one night, or just a single
```suggestion
# We might be interested in downloading all files from one night, or just a single 
```

2024-03-19 17:56 UTC, morcuended commented on docs/recipes/03_manual_reduction.py
> +# to download missing files. If the it cannot list the remote, but finds the
```suggestion
# to download missing files. If it cannot list the remote, but finds the
```

2024-03-19 17:56 UTC, morcuended commented on docs/recipes/03_manual_reduction.py
> +# both, it will return an error. This behavior can be tunned with
```suggestion
# both, it will return an error. This behavior can be tuned with 
```

2024-03-19 17:56 UTC, morcuended commented on docs/recipes/03_manual_reduction.py
> +# This will automatically select the appropiate master calibration frames from
```suggestion
# This will automatically select the appropriate master calibration frames from 
```

2024-03-19 17:56 UTC, morcuended commented on docs/recipes/03_manual_reduction.py
> +# you explicitelt pass `auto_build=True`. If you didn't, you can do it with
```suggestion
# you explicitly pass `auto_build=True`. If you didn't, you can do it with
```

2024-03-19 17:56 UTC, morcuended commented on docs/recipes/03_manual_reduction.py
> +# the raw image, and will give it an appropiate WCS. To check the result, with
```suggestion
# the raw image, and will give it an appropriate WCS. To check the result, with 
```

2024-03-19 17:56 UTC, morcuended commented on docs/recipes/04_details_on_astrometric_calibration.py
> +# it successfuly calibrates the image. When done through `build_file()`, if
```suggestion
# it successfully calibrates the image. When done through `build_file()`, if 
```

2024-03-19 17:56 UTC, morcuended commented on docs/recipes/05_quad_matching_dipol_polarimetry_images.py
> +# images is too smal for the default index files. This quad matching needs at
```suggestion
# images is too small for the default index files. This quad matching needs at 
```

2024-03-19 17:56 UTC, morcuended commented on docs/recipes/05_quad_matching_dipol_polarimetry_images.py
> +# photometry field. If any of these conditions are not met, others methods must
```suggestion
# photometry field. If any of these conditions are not met, other methods must
```

2024-03-20 13:36 UTC, morcuended commented
so what's the problem with the downloading of test data? does it have a new checksum?

2024-03-20 14:17 UTC, juanep97 commented on README.md
> +## Citing IOP4
Like this?

2024-03-20 14:21 UTC, morcuended commented on README.md
> +## Citing IOP4
Yes, I think so. Like this it should appear in the info repository like "cite this repository"

![immagine](https://github.com/juanep97/iop4/assets/32680689/8edff6ab-6c8f-4585-bfb7-7c29a0dfa974)

2024-03-20 14:26 UTC, juanep97 commented
> so what's the problem with the downloading of test data? does it have a new checksum?

It didn't set the credentials and checksum right, I think it will be solved in this CI run.

2024-03-20 14:43 UTC, morcuended commented on CITATION.cff
> +authors:
I think Jorge should be also included here. Even if not directly committing to the repository, he has contributed to it through checks, discussions, etc

2024-03-20 14:45 UTC, morcuended commented on CITATION.cff
> +authors:
if do the change, add the [no ci] previous to the commit message so the CI is not triggered again

2024-03-20 15:50 UTC, morcuended approved these changes

2024-03-20 16:38 UTC, juanep97 commented on docs/sphinxext/thumbnail_gallery.py
> +Sphinx plugin to run generate a gallery for notebooks
Because nbsphinx gallery does not pick up the thumbnails from the jupytext pct notebooks.

2024-03-20 16:39 UTC, juanep97 commented on docs/sphinxext/thumbnail_gallery.py
> +    nb_paths = glob(f"recipes/*.py")
fixed

2024-03-20 16:50 UTC, juanep97 commented
If these the tests pass, I think it is good enough for now. We can keep improving the docs in other PRs with more example notebooks, etc.

2024-03-20 16:53 UTC, morcuended commented on docs/sphinxext/thumbnail_gallery.py
> +Sphinx plugin to run generate a gallery for notebooks
right, you mentioned it

2024-03-20 16:54 UTC, morcuended approved these changes
Sure, this is good to go already. Great job

2024-03-20 17:38 UTC, merged